"""CaseKBService: false-positive and history case retrieval + archival (ISSUE-043)."""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.db import models as orm
from app.models.case import (
    HistoryCase,
    history_case_metadata,
    history_case_to_text,
    make_chunk_id,
)
from app.models.enums import EventType, FinalVerdict
from app.models.knowledge import KnowledgeChunk, RetrievedChunk
from app.models.workflow import derive_case_label
from app.services.knowledge_store import KnowledgeStore

FP_KB_NAME = "fp_case_kb"
HISTORY_KB_NAME = "history_case_kb"

# Mock-stage keyword expansions until remote embeddings land (GitHub issue #522).
_FP_KEYWORD_ALIASES: dict[str, str] = {
    "ops-change-bot": ("ops-change-bot PC-OPS-JUMP-01 bulk login change window password rotation"),
}


class CaseKBService:
    """Search false-positive and historical cases; archive closed events as cases.

    Depends on :class:`KnowledgeStore` for vector/keyword retrieval and
    :class:`async_sessionmaker` for DB reads during archival.
    """

    def __init__(
        self,
        knowledge_store: KnowledgeStore,
        session_factory: async_sessionmaker[AsyncSession],
    ) -> None:
        self._kb = knowledge_store
        self._session_factory = session_factory

    # ------------------------------------------------------------------
    # Search
    # ------------------------------------------------------------------

    async def search_fp_cases(self, alert_text: str, top_k: int = 5) -> list[RetrievedChunk]:
        """Hybrid-search ``fp_case_kb`` for false-positive patterns matching *alert_text*."""
        keyword_query = _fp_keyword_query(alert_text)
        return await self._kb.hybrid_search(
            FP_KB_NAME,
            alert_text,
            keyword_query=keyword_query,
            top_k=top_k,
        )

    async def search_history_cases(
        self,
        query_text: str,
        event_type: str | None = None,
        top_k: int = 5,
    ) -> list[RetrievedChunk]:
        """Hybrid-search ``history_case_kb``, optionally filtered by *event_type* in metadata."""
        fetch_k = top_k if event_type is None else top_k * 3
        results = await self._kb.hybrid_search(HISTORY_KB_NAME, query_text, top_k=fetch_k)
        if event_type is not None:
            results = [r for r in results if r.metadata.get("event_type") == event_type]
            results = results[:top_k]
        return results

    # ------------------------------------------------------------------
    # Archival
    # ------------------------------------------------------------------

    async def archive_event_as_case(self, event_id: str) -> str:
        """Assemble a ``HistoryCase`` from a closed event and upsert into ``history_case_kb``.

        Returns the new *case_id*.
        """
        case_id = _derive_case_id(event_id)

        async with self._session_factory() as session:
            row = await session.get(orm.SecurityEvent, event_id)
            if row is None:
                raise ValueError(f"security_event not found: {event_id}")

            event_type = EventType(row.event_type)
            verdict = FinalVerdict(row.final_verdict)
            case_label = derive_case_label(verdict)

            report = await session.scalar(select(orm.Report).where(orm.Report.event_id == event_id))

            summary = report.summary if report and report.summary else row.title
            resolution = (
                f"Report generated by {report.generated_by or 'system'}; "
                f"verdict={verdict.value}; risk_score={row.risk_score}"
                if report
                else f"Closed with verdict={verdict.value}; risk_score={row.risk_score}"
            )

            entities_raw = row.entities or {}
            entity_parts: list[str] = []
            for field in ("accounts", "hosts", "ips", "domains", "processes", "files"):
                values = entities_raw.get(field, [])
                if values:
                    rendered = ",".join(_format_entity_item(v) for v in values)
                    entity_parts.append(f"{field}={rendered}")
            key_entities = "; ".join(entity_parts) if entity_parts else "none"

            history_case = HistoryCase(
                case_id=case_id,
                event_id=event_id,
                event_type=event_type,
                case_label=case_label,
                summary=summary,
                key_entities=key_entities,
                final_verdict=verdict.value,
                risk_score=int(row.risk_score or 0),
                resolution=resolution,
                closed_at=row.closed_at or datetime.now(UTC),
            )

        content = history_case_to_text(history_case)
        chunk_id = make_chunk_id(HISTORY_KB_NAME, case_id)
        meta = history_case_metadata(history_case)

        chunk = KnowledgeChunk(
            chunk_id=chunk_id,
            kb_name=HISTORY_KB_NAME,
            content=content,
            metadata=meta,
        )
        await self._kb.upsert_chunks(HISTORY_KB_NAME, [chunk])
        return case_id


def _fp_keyword_query(alert_text: str) -> str:
    """Expand distinctive FP markers for keyword search under mock embeddings."""
    lowered = alert_text.lower()
    for needle, expansion in _FP_KEYWORD_ALIASES.items():
        if needle in lowered:
            return expansion
    return alert_text.strip()


def _format_entity_item(value: object) -> str:
    """Render an entity list item as a stable, human-readable token."""
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        for key in (
            "username",
            "hostname",
            "entity_id",
            "name",
            "ip",
            "domain",
            "path",
            "process_name",
        ):
            item = value.get(key)
            if item:
                return str(item)
    return str(value)


def _derive_case_id(event_id: str) -> str:
    """Deterministically derive a ``case-{8 hex}`` ID from an event_id."""
    digest = hashlib.sha256(event_id.encode()).hexdigest()
    return f"case-{digest[:8]}"
